// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9HRjQYGRrkZQbfMTUv3rG-ziQwRxkxE',
    appId: '1:299045261412:web:2ac96f2ac7ae132be7cf71',
    messagingSenderId: '299045261412',
    projectId: 'travelbuddy-f5a5a',
    authDomain: 'travelbuddy-f5a5a.firebaseapp.com',
    storageBucket: 'travelbuddy-f5a5a.firebasestorage.app',
    measurementId: 'G-PYZT43R0V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01BqYWKv_HQ0t7wMgNxUEkK4FLQzb4wo',
    appId: '1:299045261412:android:a8727c35ee4f9884e7cf71',
    messagingSenderId: '299045261412',
    projectId: 'travelbuddy-f5a5a',
    storageBucket: 'travelbuddy-f5a5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocQdOe66NOWoveUneTco-dl99v1d7eBA',
    appId: '1:299045261412:ios:9deb152633a9575ce7cf71',
    messagingSenderId: '299045261412',
    projectId: 'travelbuddy-f5a5a',
    storageBucket: 'travelbuddy-f5a5a.firebasestorage.app',
    iosBundleId: 'com.example.travelbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocQdOe66NOWoveUneTco-dl99v1d7eBA',
    appId: '1:299045261412:ios:9deb152633a9575ce7cf71',
    messagingSenderId: '299045261412',
    projectId: 'travelbuddy-f5a5a',
    storageBucket: 'travelbuddy-f5a5a.firebasestorage.app',
    iosBundleId: 'com.example.travelbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR9HRjQYGRrkZQbfMTUv3rG-ziQwRxkxE',
    appId: '1:299045261412:web:adcbd83ae714c27fe7cf71',
    messagingSenderId: '299045261412',
    projectId: 'travelbuddy-f5a5a',
    authDomain: 'travelbuddy-f5a5a.firebaseapp.com',
    storageBucket: 'travelbuddy-f5a5a.firebasestorage.app',
    measurementId: 'G-9EGQRX6DPT',
  );
}
